import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import { StarsBackground } from "@/components/animate-ui/stars-background";
import NextTopLoader from "nextjs-toploader";
import { Badge } from "@/components/ui/badge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        <NextTopLoader />
        {/* <StarsBackground className="absolute inset-0" /> */}
        <Header />
        <main className="container">{children}</main>
        <footer className="py-10">
          <div className="container flex justify-center items-center">
            <Badge variant="default" shiny >
              Made with ❤️ by PhatJack
            </Badge>
          </div>
        </footer>
      </body>
    </html>
  );
}
